### PR TITLE
Remove camlp4 dependency and add cppo dependency

### PR DESCRIPTION
**Pull request by abate**
tested with Ocaml 4.01.0 and Ocaml 4.02.1

### CODE REVIEW

**Comment by ygrek** [comment]
this also includes some Bytes-related changes - why?

**Comment by abate** [comment]
in order to compile unzip, The Bytes module is needed and since this is provided by the module ExtBytes I had to modify the name space. This is the reason, unless I missed something obvious ...

**Comment by ygrek** [comment]
Hm, I will check, but can you make it a separate change?
I am ok with camlp4 to cppo switch as camlp4 is no longer available by default, but the ExtBytes code is wip

**Comment by abate** [comment]
The first patch does not compile : 

File "unzip.mli", line 45, characters 24-31:
Error: Unbound module Bytes
Makefile:42: recipe for target 'unzip.cmo' failed
make: *** [unzip.cmo] Error 2

**Comment by ygrek** [comment]
Hm, I cannot reproduce this build failure. What is the version of ocaml and ocamlfind that you have?

**Comment by ygrek** [comment]
Ok, I tested now with `install.ml` and with older OCaml versions, looks like all setups are covered. Thank you!

**Comment by abate** [comment]
I still get an error ...

$git clone https://github.com/ygrek/ocaml-extlib.git
Cloning into 'ocaml-extlib'...
remote: Counting objects: 2103, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2103 (delta 8), reused 0 (delta 0), pack-reused 2085
Receiving objects: 100% (2103/2103), 441.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1137/1137), done.
Checking connectivity... done.
$cd ocaml-extlib/src/
$make
cppo -D OCAML4  extBytes.mlpp -o extBytes.ml
ocamlc -i extBytes.ml > extBytes.mli
ocamlfind ocamlc -g -package bytes -c extBytes.mli extBytes.ml
ocamlfind: Package `bytes' not found
Makefile:42: recipe for target 'extBytes.cmo' failed
make: *** [extBytes.cmo] Error 2

this is the ocaml compiler I'm using
$ocamlc -v
The OCaml compiler, version 4.01.0
Standard library directory: /usr/lib/ocaml

Debian unstable.

The problem is that OCAMLC and OCAMLOPT use by default ```-package bytes``` and the module Bytes is not available in OCaml 4.01.0 if I'm not mistaken...

**Comment by ygrek** [comment]
afaik `bytes` is provided by ocamlfind and `opam` package for extlib depends on the recent enough ocamlfind to build cleanly. We can either detect and handle the absence of `bytes` package or error out and require newer ocamlfind..

**Comment by abate** [comment]
yes, with opam 1.2 (switch system) and ocaml 4.01.0 (debian unstable) you can install the opam module ```base-bytes.legacy``` . But if you add this dependency, I don't see why you should nother with this conditional compilation statements ... My point is, if you add ExtBytes as a backward compatibility layer, you should not need the module Bytes at all. If you add this module as a dependency to extlib with ocaml < 4.02.2 as you are suggesting, you don't need to add the conditional compilation statement to ExtBytes.ml . Maybe I'm missing something very obvious here.

**Comment by ygrek** [comment]
I think you are correct, I will prefer to remove conditional compilation and just require extlib users to have ocamlfind package `bytes` installed (which is provided by `ocamlfind` >= 1.5.1 and is represented by opam package `base-bytes`).

**Comment by ygrek** [comment]
Argh, I forgot one more factor, `install.ml` has a mode of compilation without ocamlfind. So currently when one builds with Makefile - `bytes` is  a dependency and it is available for all OCaml versions with recent enough `ocamlfind. But when building with `install.ml` it will use `ExtBytes` implementation and no dependencies. I guess this covers all users and no more changes required.. Only need to document this in README

**Pull request closed without merging**
