### PR TITLE
fix `IO.read_bits 31 ch` (closes #50)

### LINKED ISSUE #50: IO.read_bits fails when reading exactly 31 bits
IIUC, this should say `>`, not `>=`
https://github.com/ygrek/ocaml-extlib/blob/103ff096ff2c570411fae3b19032f03e2d86fd2b/src/IO.ml#L755

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by ygrek** [comment]
Thanks!

**Comment by nadako** [comment]
Thanks for merging! Can we have a release soon-ish? :)

**Comment by ygrek** [comment]
sure, but need to fix 32-bit build first

**Comment by ygrek** [comment]
https://github.com/ocaml/opam-repository/pull/13572

**Pull request merged**
