### PR TITLE
Add support for OCaml 5.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Same as https://github.com/ygrek/ocaml-extlib/pull/57 (reimplemented independently because i forgot to check the opened PRs) but with OCaml < 4.07 compatibility and fixed tests

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
@ygrek could we get a release? If I can help in any way, please let me know.

**Comment by ygrek** [comment]
I want to get other changes from the dune PR in. If I don't get to it soon - will cut a release as is

**Comment by ygrek** [comment]
pushed tag 1.7.9

**Comment by kit-ty-kate** [comment]
Thanks a lot! I opened PR for for the release on opam here: https://github.com/ocaml/opam-repository/pull/21946

**Pull request merged**
